scannerTester: scanner.o scannerTester.o
	    g++ -g -o scannerTester scanner.o scannerTester.o 

scannerTester.o: scannerTester.cc
	    g++ -g  -c scannerTester.cc

scanner.o: ../scanner.cc ../scanner.h
	    g++ -g  -c ../scanner.cc

